server:
  port: 8091

spring:
  security:
    basic:
      enabled: false
  temporal:
    connection:
      target: 127.0.0.1:7233
    workers:
      - task-queue: GreetingTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 10
      max-threads: 10
    workersAutoDiscovery:
      packages: com.rohitpothuri.rbac.workflows

  ## default connection pool
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: lucky9314
    ## default connection pool
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # this can be used for testing
      ddl-auto: create-drop
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  main:
    lazy-initialization: true
#
#  # create and drop table, good for testing, production set to none or comment it
#  spring.jpa.hibernate.ddl-auto=create-drop

logging:
  level:
    root: info

management:
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

scrape_configs:
  - job_name: 'aerbac-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: "none"

