server:
  port: 8091
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:classpath:/h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      # this can be used for testing
      ddl-auto: create
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  main:
    lazy-initialization: true
#
#  # create and drop table, good for testing, production set to none or comment it
#  spring.jpa.hibernate.ddl-auto=create-drop

logging:
  level:
    root: info

management:
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

scrape_configs:
  - job_name: 'aerbac-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: "none"

