server:
  port: 8091

spring:
  security:
    user:
     name: admin
     password: admin

## default connection pool
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: lucky9314
    ## default connection pool
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # this can be used for testing
      ddl-auto: create-drop
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  main:
    lazy-initialization: true
#
#  # create and drop table, good for testing, production set to none or comment it
#  spring.jpa.hibernate.ddl-auto=create-drop

logging:
  level:
    root: info

management:
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

scrape_configs:
  - job_name: 'aerbac-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

springdoc:
  show-actuator: true
  swagger-ui:
    doc-expansion: "none"

